variables:
- ${{ if eq( variables['Build.SourceBranchName'],'PDD' ) }}:
   - group: CD-PDD
- ${{ if eq( variables['Build.SourceBranchName'],'PREPDD') }}:
   - group: CD-PREPDD

resources:
  repositories:
     - repository: deploy
       type: git
       name: DevOps/DespliegueAutomatico
       ref: "main"

stages:
- template: azure-pipelines.yml@deploy
